name: Documentation for pygeosolve

on: [push]

jobs:
  docs:
    name: Build documentation
    runs-on: Ubuntu-latest
    steps:
    - name: Get source code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package
      run: |
        python -m pip install .[dev]
    - name: Build documentation
      run: |
        cd docs
        make html
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs/build/html

  deploy-docs:
    name: Deploy documentation on GitHub pages
    runs-on: Ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')  # Only run for tags.
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: documentation
        path: docs
    - uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: docs
