name: Documentation for pygeosolve

on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build and deploy documentation
    runs-on: ubuntu-latest
    steps:
    - name: Get source code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package
      run: |
        python -m pip install .[dev]
    - name: Build documentation
      run: |
        cd docs
        make html
    - uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: docs/build/html
